### ISSUE TITLE
Print chain of causes

### ISSUE THREAD

**Issue by link2xt** [wiktor-k/testresult#6]
Anyhow errors are much more interesting to print with `{:#}` because this prints the chain of underlying causes rather than the last `.context()`: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations

There is however no way to get this from TestResult output as it formats the error with the default representation: https://github.com/wiktor-k/testresult/blob/506173df603f89f030b140e63318713118970239/src/lib.rs#L18

**Comment by wiktor-k** [comment]
Yep. This is because TestResult works for stuff that implements Display but now I think that it may be possible to extend it to stuff that implements Debug (since that's also required for Errors).

Thanks for opening the issue. Even though you solved your problem in a different way I'd like this issue to be stay open if you don't mind.

:wave:
